backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: {{year}}-{{month}}-{{day}}-{{slug}}
    fields:
      - { name: templateKey, label: Template Key, widget: 'hidden', default: 'blog-post' }
      - { name: title, label: Title, widget: "string" }
      - { name: date, label: Publish Date, widget: datetime }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list }